[package]
name = "shanten_count"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = "2.1.1"
proconio = { version = "=0.5.0", features = ["derive"] }
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"